In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

print("설치 완료!")

설치 완료!

In [2]:
import sklearn

print(sklearn.__version__)

1.9.0

In [3]:
data = pd.read_csv(r'D:\19\adult.csv')

In [4]:
data.head()

,age,workclass,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K.
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K.
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K.
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K.
4,18,?,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K.

In [5]:
data.tail()

,age,workclass,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
48837,27,Private,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       48842 non-null  str
 2   education       48842 non-null  str
 3   education.num   48842 non-null  int64
 4   marital.status  48842 non-null  str
 5   occupation      48842 non-null  str
 6   relationship    48842 non-null  str
 7   race            48842 non-null  str
 8   sex             48842 non-null  str
 9   capital.gain    48842 non-null  int64
 10  capital.loss    48842 non-null  int64
 11  hours.per.week  48842 non-null  int64
 12  native.country  48842 non-null  str
 13  income          48842 non-null  str
dtypes: int64(5), str(9)
memory usage: 5.2 MB

In [7]:
data.describe()

                age  education.num  capital.gain  capital.loss  hours.per.week
count  48842.000000   48842.000000  48842.000000  48842.000000    48842.000000
mean      38.643585      10.078089   1079.067626     87.502314       40.422382
std       13.710510       2.570973   7452.019058    403.004552       12.391444
min       17.000000       1.000000      0.000000      0.000000        1.000000
25%       28.000000       9.000000      0.000000      0.000000       40.000000
50%       37.000000      10.000000      0.000000      0.000000       40.000000
75%       48.000000      12.000000      0.000000      0.000000       45.000000
max       90.000000      16.000000  99999.000000   4356.000000       99.000000

In [8]:
data['income'].unique()

<StringArray>
[' <=50K.', ' >50K.', ' <=50K', ' >50K']
Length: 4, dtype: str

In [9]:
data['income'].nunique()

4

In [11]:
data['income'].value_counts()

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [ ]:
data.isna().sum()  #결측치 갯수

age               0
workclass         0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [ ]:
data.isna().mean()   # 결측치 비율

age               0.0
workclass         0.0
education         0.0
education.num     0.0
marital.status    0.0
occupation        0.0
relationship      0.0
race              0.0
sex               0.0
capital.gain      0.0
capital.loss      0.0
hours.per.week    0.0
native.country    0.0
income            0.0
dtype: float64

In [14]:
data.isin(['?']).sum()

age               0
workclass         0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [15]:
# X와 y 분리

X = data.drop('income', axis = 1)
y = data['income']

In [19]:
# 범주형 데이터 중 명목형 인코딩인 원핫인코딩 이용

X = pd.get_dummies(X, drop_first = True)

X.shape
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 99 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   age                                         48842 non-null  int64
 1   education.num                               48842 non-null  int64
 2   capital.gain                                48842 non-null  int64
 3   capital.loss                                48842 non-null  int64
 4   hours.per.week                              48842 non-null  int64
 5   workclass_ Federal-gov                      48842 non-null  bool
 6   workclass_ Local-gov                        48842 non-null  bool
 7   workclass_ Never-worked                     48842 non-null  bool
 8   workclass_ Private                          48842 non-null  bool
 9   workclass_ Self-emp-inc                     48842 non-null  bool
 10  workclass_ Self-emp-not-inc                 48842 non-null  bool
 11  workclass_ State-gov                        48842 non-null  bool
 12  workclass_ Without-pay                      48842 non-null  bool
 13  education_ 11th                             48842 non-null  bool
 14  education_ 12th                             48842 non-null  bool
 15  education_ 1st-4th                          48842 non-null  bool
 16  education_ 5th-6th                          48842 non-null  bool
 17  education_ 7th-8th                          48842 non-null  bool
 18  education_ 9th                              48842 non-null  bool
 19  education_ Assoc-acdm                       48842 non-null  bool
 20  education_ Assoc-voc                        48842 non-null  bool
 21  education_ Bachelors                        48842 non-null  bool
 22  education_ Doctorate                        48842 non-null  bool
 23  education_ HS-grad                          48842 non-null  bool
 24  education_ Masters                          48842 non-null  bool
 25  education_ Preschool                        48842 non-null  bool
 26  education_ Prof-school                      48842 non-null  bool
 27  education_ Some-college                     48842 non-null  bool
 28  marital.status_ Married-AF-spouse           48842 non-null  bool
 29  marital.status_ Married-civ-spouse          48842 non-null  bool
 30  marital.status_ Married-spouse-absent       48842 non-null  bool
 31  marital.status_ Never-married               48842 non-null  bool
 32  marital.status_ Separated                   48842 non-null  bool
 33  marital.status_ Widowed                     48842 non-null  bool
 34  occupation_ Adm-clerical                    48842 non-null  bool
 35  occupation_ Armed-Forces                    48842 non-null  bool
 36  occupation_ Craft-repair                    48842 non-null  bool
 37  occupation_ Exec-managerial                 48842 non-null  bool
 38  occupation_ Farming-fishing                 48842 non-null  bool
 39  occupation_ Handlers-cleaners               48842 non-null  bool
 40  occupation_ Machine-op-inspct               48842 non-null  bool
 41  occupation_ Other-service                   48842 non-null  bool
 42  occupation_ Priv-house-serv                 48842 non-null  bool
 43  occupation_ Prof-specialty                  48842 non-null  bool
 44  occupation_ Protective-serv                 48842 non-null  bool
 45  occupation_ Sales                           48842 non-null  bool
 46  occupation_ Tech-support                    48842 non-null  bool
 47  occupation_ Transport-moving                48842 non-null  bool
 48  relationship_ Not-in-family                 48842 non-null  bool
 49  relationship_ Other-relative                48842 non-null  bool
 50  relationship_ Own-child                     48842 non-null  bool
 51  relationship_ Unmarried                     48842 non-null  bool
 52  relationship_ Wife                          48842 non-null  bool
 53  race_ Asian-Pac-Islander                    48842 non-null  bool
 54  race_ Black                                 48842 non-null  bool
 55  race_ Other                                 48842 non-null  bool
 56  race_ White                                 48842 non-null  bool
 57  sex_ Male                                   48842 non-null  bool
 58  native.country_ Cambodia                    48842 non-null  bool
 59  native.country_ Canada                      48842 non-null  bool
 60  native.country_ China                       48842 non-null  bool
 61  native.country_ Columbia                    48842 non-null  bool
 62  native.country_ Cuba                        48842 non-null  bool
 63  native.country_ Dominican-Republic          48842 non-null  bool
 64  native.country_ Ecuador                     48842 non-null  bool
 65  native.country_ El-Salvador                 48842 non-null  bool
 66  native.country_ England                     48842 non-null  bool
 67  native.country_ France                      48842 non-null  bool
 68  native.country_ Germany                     48842 non-null  bool
 69  native.country_ Greece                      48842 non-null  bool
 70  native.country_ Guatemala                   48842 non-null  bool
 71  native.country_ Haiti                       48842 non-null  bool
 72  native.country_ Holand-Netherlands          48842 non-null  bool
 73  native.country_ Honduras                    48842 non-null  bool
 74  native.country_ Hong                        48842 non-null  bool
 75  native.country_ Hungary                     48842 non-null  bool
 76  native.country_ India                       48842 non-null  bool
 77  native.country_ Iran                        48842 non-null  bool
 78  native.country_ Ireland                     48842 non-null  bool
 79  native.country_ Italy                       48842 non-null  bool
 80  native.country_ Jamaica                     48842 non-null  bool
 81  native.country_ Japan                       48842 non-null  bool
 82  native.country_ Laos                        48842 non-null  bool
 83  native.country_ Mexico                      48842 non-null  bool
 84  native.country_ Nicaragua                   48842 non-null  bool
 85  native.country_ Outlying-US(Guam-USVI-etc)  48842 non-null  bool
 86  native.country_ Peru                        48842 non-null  bool
 87  native.country_ Philippines                 48842 non-null  bool
 88  native.country_ Poland                      48842 non-null  bool
 89  native.country_ Portugal                    48842 non-null  bool
 90  native.country_ Puerto-Rico                 48842 non-null  bool
 91  native.country_ Scotland                    48842 non-null  bool
 92  native.country_ South                       48842 non-null  bool
 93  native.country_ Taiwan                      48842 non-null  bool
 94  native.country_ Thailand                    48842 non-null  bool
 95  native.country_ Trinadad&Tobago             48842 non-null  bool
 96  native.country_ United-States               48842 non-null  bool
 97  native.country_ Vietnam                     48842 non-null  bool
 98  native.country_ Yugoslavia                  48842 non-null  bool
dtypes: bool(94), int64(5)
memory usage: 6.2 MB

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.4, random_state= 42
)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

pred = dt.predict(X_test)

acc = accuracy_score(y_test, pred)

acc

0.46209755847878387

In [21]:
y.unique()

<StringArray>
[' <=50K.', ' >50K.', ' <=50K', ' >50K']
Length: 4, dtype: str

In [22]:
y.value_counts()

income
<=50K     24720
<=50K.    12435
>50K       7841
>50K.      3846
Name: count, dtype: int64

In [23]:
X.shape

(48842, 99)

In [24]:
y.shape

(48842,)

In [ ]:
# acc의 결과 값이 너무 낮게 나와 y의 클래스를 확인한 결과, 
# 공백과 마침표 때문에 동일한 클래스가 서로 다르게 인식됨
# y 정리: 앞 뒤 공백 제거+마침표 제거

y = y.str.strip().str.replace('.', '', regex = False)

y.unique()
y.value_counts()

income
<=50K    37155
>50K     11687
Name: count, dtype: int64

In [26]:
# train, test 다시 분할

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size= 0.4, random_state= 42, stratify = y
)

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

pred = dt.predict(X_test)

acc = accuracy_score(y_test, pred)

acc

0.821364590264626