In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. 유방암 데이터 불러오기
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

In [2]:
print(cancer.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
cancer.head()

# 에러가 난 이유:
# data = pd.read_csv(r'D:\18\wine.csv'); data.head()의 경우
# pandas dataframe이라 'head()'가 사용가능하지만,
# breast cancer는 내장 데이터셋의 bunch 객체라 dataframe으로 변환한 뒤 분석가능.

AttributeError: head

In [ ]:
# 2. DataFrame으로 변환

data = pd.DataFrame(
    cancer.data, columns = cancer.feature_names)

data['target'] = cancer.target

print(type(data))

<class 'pandas.DataFrame'>

In [ ]:
# 3. 데이터 확인(head, info, tail, describe)
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [8]:
data.tail()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [9]:
data.describe()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
count,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,0.062798,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,0.627417
std,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,0.007060,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,0.483918
min,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,0.049960,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,0.000000
25%,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,0.057700,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,0.000000
50%,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,0.061540,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,1.000000
75%,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,0.066120,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,1.000000
max,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,0.097440,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,1.000000

In [ ]:
# 4. 결측치 갯수 확인
data.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
# 5. 종속변수(열 이름: target) 확인
data['target'].unique()

array([0, 1])

In [11]:
data['target'].nunique()

2

In [12]:
data['target'].value_counts()

target
1    357
0    212
Name: count, dtype: int64

In [13]:
print(cancer.target_names)

['malignant' 'benign']

In [ ]:
# 6. 독립변수(X), 종속변수(y) 설정

X = data.drop('target', axis= 1)
y = data['target']

print(X.shape)   # X의 행과 열의 갯수 확인
print(y.shape)

(569, 30)
(569,)

In [18]:
# 7. 데이터를 학습용(Train)과 시험용(test)로 나누기
# 데이터를 학습용(80%)과 테스트용(20%)으로 분리
# stratify=y를 사용하여 y(정답)의 비율을 유지하면서 데이터 나누기

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state= 42, stratify = y)

In [ ]:
# 8. 스케일링 없이 KNN
# [미션 1] 스케일링 없이 베이스라인

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

pred = knn.predict(X_test)

accuracy = accuracy_score(y_test, pred)

accuracy

0.9122807017543859

In [ ]:
# 9-1. 표준화 스케일링(StandardScaler) 적용 

from sklearn.preprocessing import StandardScaler

st_scaler = StandardScaler()

# StandardScaler 적용된 학습데이터
# 학습데이터를 평균과 표준편차계산(fit) 후 실제 표준화 수행(transform)
X_train_st = st_scaler.fit_transform(X_train) 

# StandardScaler 적용된 테스터데이터
# 시험데이터(X_test)는 정보를 미리 보면 안되기 때문에(데이터 누수방지) transform만 함
# 학습데이터의 기준(평균, 표준편차)을 이용하여 테스트 데이터를 표준화
X_test_st = st_scaler.transform(X_test)

st_scaled_df = pd.DataFrame(X_train_st, columns= X_train.columns)

round(st_scaled_df.describe(), 2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
count,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,...,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00
mean,-0.00,0.00,-0.00,-0.00,0.00,-0.00,-0.00,0.00,-0.00,0.00,...,0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-2.03,-2.17,-1.98,-1.47,-2.50,-1.58,-1.09,-1.24,-2.66,-1.80,...,-1.73,-2.19,-1.70,-1.24,-2.72,-1.42,-1.28,-1.71,-2.08,-1.57
25%,-0.70,-0.74,-0.70,-0.68,-0.72,-0.75,-0.75,-0.72,-0.67,-0.72,...,-0.66,-0.73,-0.69,-0.64,-0.73,-0.68,-0.78,-0.76,-0.64,-0.66
50%,-0.23,-0.10,-0.23,-0.31,-0.04,-0.24,-0.36,-0.40,-0.09,-0.19,...,-0.27,-0.04,-0.27,-0.34,-0.04,-0.27,-0.22,-0.25,-0.14,-0.22
75%,0.48,0.56,0.50,0.35,0.65,0.49,0.53,0.66,0.52,0.48,...,0.50,0.60,0.55,0.30,0.62,0.52,0.50,0.73,0.45,0.44
max,4.02,4.55,4.02,5.37,3.61,4.52,4.13,3.93,4.40,4.84,...,3.56,3.84,3.70,4.64,3.82,5.03,4.52,2.65,5.78,6.72

In [ ]:
# 9-2. StandardScaler 적용후 KNN 
# [미션2-1] StandardScaler 스케일링 전후 비교: 전은 0.91, 후는 0.96

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn_st = KNeighborsClassifier()

knn_st.fit(X_train_st, y_train)

pred_st = knn_st.predict(X_test_st)

accuracy_st = accuracy_score(y_test, pred_st)

print(round(accuracy,2 ))
print(round(accuracy_st, 2))

0.91
0.96

In [ ]:
# 9-3. 혼동행렬(Confusion Matrix) 비교: 악성 환자를 몇 명 놓쳤는 지 확인
# 특히 암 데이터에서는 악성환자(0)를 놓친 수(False Negative)를 확인하는 것이 중요.

# [미션2-2] 악성을 놓친 환자 수 비교: 
# 스케일링 없는 혼동행렬의 결과는 4명을 놓치고, 
# StandardScaler 적용한 혼동행렬은 3명의 암환자를 놓침

from sklearn.metrics import confusion_matrix

# 스케일링 없이 KNN의 혼동행렬 
cm = confusion_matrix(y_test, pred)   
print(cm)

# StandardScaler 적용 후 KNN의 혼동행렬 
cm_st = confusion_matrix(y_test, pred_st)
print(cm_st)

# 0=악성(Malignant) / 1=양성(Benign)

#               예측값(predicted)
#               0           1 
# 실제값 0      [39]        [3]         
# 실제값 1      [2]         [70]    

# 암환자 39명을 정확하게 찾아냈지만, 암환자 3명을 놓침!!! 
# 건강한 사람 2명을 암환자로 오진하고, 양성 환자 70명을 정확하게 분류함.

# '악성을 놓친 환자 수'의 전후 비교: 
# 표준화스케일링을 적용한 KNN모델은 실제 악성 환자 3명을 양성으로 잘못 예측하였음!

[[38  4]
 [ 6 66]]
[[39  3]
 [ 2 70]]

In [ ]:
# 10-1. 최소-최대 스케일링(MinMaxScaler) 적용

from sklearn.preprocessing import MinMaxScaler

mm_scaler = MinMaxScaler()

X_train_mm = mm_scaler.fit_transform(X_train)
X_test_mm = mm_scaler.transform(X_test)

mm_scaled_df = pd.DataFrame(X_train_mm, columns=X_train.columns)

round(mm_scaled_df.describe(), 2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
count,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,...,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00
mean,0.34,0.32,0.33,0.21,0.41,0.26,0.21,0.24,0.38,0.27,...,0.33,0.36,0.31,0.21,0.42,0.22,0.22,0.39,0.26,0.19
std,0.17,0.15,0.17,0.15,0.16,0.16,0.19,0.19,0.14,0.15,...,0.19,0.17,0.19,0.17,0.15,0.16,0.17,0.23,0.13,0.12
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.22,0.21,0.21,0.12,0.29,0.14,0.07,0.10,0.28,0.16,...,0.20,0.24,0.19,0.10,0.30,0.12,0.09,0.22,0.18,0.11
50%,0.30,0.31,0.29,0.17,0.40,0.22,0.14,0.16,0.36,0.24,...,0.28,0.36,0.26,0.15,0.41,0.18,0.18,0.33,0.25,0.16
75%,0.41,0.41,0.41,0.27,0.52,0.34,0.31,0.37,0.45,0.34,...,0.42,0.46,0.42,0.26,0.51,0.30,0.31,0.56,0.32,0.24
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [32]:
# 10-2. MinMaxScaler 적용 후 KNN

knn_mm = KNeighborsClassifier()

knn_mm.fit(X_train_mm, y_train)
pred_mm = knn_mm.predict(X_test_mm)

accuracy_mm = accuracy_score(y_test, pred_mm)

print(round(accuracy_mm, 2))

0.98

In [34]:
# 11-1. 로버스트 스케일링(RobustScaler) 적용

from sklearn.preprocessing import RobustScaler

rb_scaler = RobustScaler()

X_train_rb = rb_scaler.fit_transform(X_train)
X_test_rb = rb_scaler.transform(X_test)

rb_scaler_df = pd.DataFrame(X_train_rb, columns= X_train.columns)

round(rb_scaler_df.describe(), 2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
count,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,...,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00,455.00
mean,0.19,0.07,0.19,0.30,0.03,0.19,0.28,0.29,0.08,0.16,...,0.23,0.03,0.22,0.36,0.03,0.22,0.17,0.17,0.13,0.20
std,0.85,0.77,0.83,0.97,0.73,0.81,0.78,0.73,0.84,0.84,...,0.86,0.75,0.81,1.06,0.75,0.84,0.78,0.67,0.91,0.91
min,-1.53,-1.60,-1.46,-1.12,-1.80,-1.08,-0.58,-0.61,-2.15,-1.34,...,-1.26,-1.62,-1.14,-0.96,-1.99,-0.97,-0.83,-0.98,-1.77,-1.23
25%,-0.40,-0.49,-0.39,-0.36,-0.50,-0.41,-0.31,-0.23,-0.49,-0.44,...,-0.34,-0.52,-0.34,-0.33,-0.51,-0.34,-0.44,-0.34,-0.46,-0.40
50%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,0.60,0.51,0.61,0.64,0.50,0.59,0.69,0.77,0.51,0.56,...,0.66,0.48,0.66,0.67,0.49,0.66,0.56,0.66,0.54,0.60
max,3.62,3.58,3.54,5.52,2.67,3.83,3.52,3.14,3.75,4.20,...,3.29,2.92,3.19,5.29,2.88,4.43,3.68,1.96,5.40,6.30

In [35]:
# 11-2. RobustScaler 적용 후 KNN

knn_rb = KNeighborsClassifier()

knn_rb.fit(X_train_rb, y_train)

pred_rb = knn_rb.predict(X_test_rb)

accuracy_rb = accuracy_score(y_test, pred_rb)

print(round(accuracy_rb, 2))

0.95

In [ ]:
# [미션 3-1] 세 스케일러 비교 및 해석

print(round(accuracy,2 ))       # 스케일링 x
print(round(accuracy_st, 2))    # StandardScaler(표준화)
print(round(accuracy_mm, 2))    # MinMaxScaler(최소최대)
print(round(accuracy_rb, 2))    # RobustScaler(로버스트)

# MinMaxScaler가 가장 높은 정확도를 나타냄.
# 세 가지 스케일링 방법의 차이가 크지 않은 이유는 
# 유방암 데이터가 대부분 수치형 변수로 구성되어 있으며, 극단적인 이상치가 많지 않기 때문임
# 따라서, 세 가지 스케일러 모두 안정적인 성능을 보인 것으로 해석 할 수 있음.

0.91
0.96
0.98
0.95

In [ ]:
# [미션 3-2] K=1~20 정확도를 비교

std_scores = []
mm_scores = []
rb_scores = []

for k in range(1, 21) :
    
    # StandardScaler
    knn_st = KNeighborsClassifier(n_neighbors=k)
    knn_st.fit(X_train_st, y_train)
    pred_st = knn_st.predict(X_test_st)
    std_scores.append(accuracy_score(y_test, pred_st))
    
    # MinMaxScaler
    knn_mm = KNeighborsClassifier(n_neighbors=k)
    knn_mm.fit(X_train_mm, y_train)
    pred_mm = knn_mm.predict(X_test_mm)
    mm_scores.append(accuracy_score(y_test, pred_mm))
    
    # RobustScaler
    knn_rb = KNeighborsClassifier(n_neighbors=k)
    knn_rb.fit(X_train_rb, y_train)
    pred_rb = knn_rb.predict(X_test_rb)
    rb_scores.append(accuracy_score(y_test, pred_rb))
    
    print(f"K = {k:2d} | "
          f"Standard = {std_scores[k-1]: .2f} | "
          f"MinMax = {mm_scores[k-1]: .2f} | "
          f"Robust = {rb_scores[k-1]: .2f}")
    
print("Standard 최고 정확도: ", max(std_scores))
print("MinMax 최고 정확도: ", max(mm_scores))
print("Robust 최고 정확도: ", max(rb_scores))

# 결과:
# StandardScaler의 최고 정확도는 98.25%이며, 최고 K값은 3, 17, 18임.
# MinMaxScaler의 최고 정확도는 98.25%이며, 최고 K값은 5, 12, 13, 17~20임.
# RobustScaler의 최고 정확도는 97.37%이며, 최고 K값은 7, 9~13, 17, 19, 20임.
# 해석: StandardScaler = MinMaxScaler > RobustScaler

K =  1 | Standard =  0.94 | MinMax =  0.94 | Robust =  0.92
K =  2 | Standard =  0.93 | MinMax =  0.94 | Robust =  0.89
K =  3 | Standard =  0.98 | MinMax =  0.96 | Robust =  0.96
K =  4 | Standard =  0.95 | MinMax =  0.96 | Robust =  0.93
K =  5 | Standard =  0.96 | MinMax =  0.98 | Robust =  0.95
K =  6 | Standard =  0.96 | MinMax =  0.96 | Robust =  0.94
K =  7 | Standard =  0.97 | MinMax =  0.97 | Robust =  0.97
K =  8 | Standard =  0.97 | MinMax =  0.96 | Robust =  0.96
K =  9 | Standard =  0.97 | MinMax =  0.96 | Robust =  0.97
K = 10 | Standard =  0.96 | MinMax =  0.97 | Robust =  0.97
K = 11 | Standard =  0.97 | MinMax =  0.97 | Robust =  0.97
K = 12 | Standard =  0.97 | MinMax =  0.98 | Robust =  0.97
K = 13 | Standard =  0.97 | MinMax =  0.98 | Robust =  0.97
K = 14 | Standard =  0.96 | MinMax =  0.97 | Robust =  0.96
K = 15 | Standard =  0.97 | MinMax =  0.97 | Robust =  0.96
K = 16 | Standard =  0.97 | MinMax =  0.97 | Robust =  0.96
K = 17 | Standard =  0.98 | MinMax =  0.98 | Robust =  0.97
K = 18 | Standard =  0.98 | MinMax =  0.98 | Robust =  0.96
K = 19 | Standard =  0.97 | MinMax =  0.98 | Robust =  0.97
K = 20 | Standard =  0.97 | MinMax =  0.98 | Robust =  0.97
Standard 최고 정확도:  0.9824561403508771
MinMax 최고 정확도:  0.9824561403508771
Robust 최고 정확도:  0.9736842105263158